title: Amy Crighton
# email: hello@phonebox.theatre 
description: >- # this means to ignore newlines until "baseurl:"
  Amy Crighton is an emerging director based in Warwickshire. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: amycrighton
github_username:  samozzy


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

strict_front_matter: true 
livereload: true 

plugins:
  - bootstrap 

sass:
    sass_dir: _sass
    style: expanded 

collections:
  content:
    output: true
    permalink: :path/
  shows:
    output: true 
    permalink: /shows/:path
permalink: pretty 

defaults:
  # Defaults for pages
  - scope:
      type: content
    values:
      layout: default
